spring:
  application:
    name: authentication-service
  config:
    import: optional:configserver:${CONFIG_SERVER}
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true